version: "3.7"

services:
  web:
    image : benjaminkrueger/kringle-web
    environment:
      - POSTGRES_URL=kringle_database:5432
      - POSTGRES_USER=kringle
      - POSTGRES_PW=kringle
      - POSTGRES_DB=kringle
      - SECRET_KEY=secret-key-goes-here
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - S3_ENDPOINT=http://minio:9000
      - S3_FOLDER=http://localhost:9000/kringle-public
      - S3_QUOTA=100
      - BUCKET_PUBLIC=kringle-public
      - BUCKET_PRIVATE=kringle-private
      - WWW_SERVER=http://localhost:5010
      - MAIL_ENABLE=0
      - MAIL_SERVER=localhost
      - MAIL_SENDER=mail@localhost
      - MAIL_ADMIN=admin@localhost
      - APP_VERSION=1.1
      - APP_PREFIX=
    command: sh /home/kringle/flask.sh
    user: kringle
    ports:
      - "127.0.0.1:5010:5010"
    container_name: kringle_web
    volumes:
      - ./.aws/:/home/kringle/.aws/

  database:
    image: postgres
    environment:
      - POSTGRES_USER=kringle
      - POSTGRES_PASSWORD=kringle
    ports:
      - "127.0.0.1:5432:5432"
    container_name: kringle_database
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
#      - ./db/kringle.dump:/tmp/kringle.dump

  minio:
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9010:9010"
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    container_name: kringle_s3
    volumes:
      - s3:/data
    command: server --address ":9000" --console-address ":9010" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    container_name: kringle_buckets
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add kringle http://minio:9000 minio_access_key minio_secret_key) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb kringle/kringle-private/;
      /usr/bin/mc mb kringle/kringle-public/;
      /usr/bin/mc anonymous set public kringle/kringle-public;
      echo EMPTY > empty.txt;
      /usr/bin/mc cp empty.txt kringle/kringle-public/user/empty.txt;
      /usr/bin/mc cp empty.txt kringle/kringle-public/world/empty.txt;
      exit 0;
      "

volumes:
  db:
    driver: local
  s3:
    driver: local
