version: "3.7"

services:
  web:
    image : benjaminkrueger/kringle-web
    environment:
      - POSTGRES_URL=kringle_database:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PW=postgres
      - POSTGRES_DB=postgres
      - SECRET_KEY=secret-key-goes-here
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - S3_ENDPOINT=https://s3.hidrive.strato.com
      - BUCKET_PUBLIC=kringle-public
      - BUCKET_PRIVATE=kringle-private
      - MAIL_SERVER=host.docker.internal
    command: /home/flask/flask.sh
    user: flask
    ports:
      - 127.0.0.1:5010:5010
    container_name: kringle_web
    volumes:
      - ./.aws/:/home/flask/.aws/
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5432:5432
    container_name: kringle_database
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local
