site_name: Kringle Web
site_url: https://kringle.info/static/doc/
site_dir: ./static/mkdocs
use_directory_urls: false
nav:
    - Home: index.md
    - About: about.md
theme: readthedocs
favicon: 'img/favicon.ico'
